"""Assemble exact XRT public headers and a DEF, without installing anything."""
from pathlib import Path, PurePosixPath
import datetime
import hashlib
import json
import re
import tarfile

BASE = Path(__file__).resolve().parent
R7 = BASE.parent
REVISION = "42cba83aee86b253c49eccd484646e91d062468d"
ARCHIVE = R7 / "sources/metering/xrt_exact.tar.gz"
EXPECTED_ARCHIVE = "971e612a83c0d8c848ab1f5a78e03db53f5a1568bb96b1553150f387c78a1d3d"
PREFIX = f"XRT-{REVISION}/src/runtime_src/core/include/"
ROOTS = ["xrt/xrt_device.h", "xrt/xrt_kernel.h", "xrt/xrt_bo.h",
         "xrt/xrt_hw_context.h", "experimental/xrt_xclbin.h"]

def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()

assert sha256(ARCHIVE) == EXPECTED_ARCHIVE, "Source archive hash mismatch"
with tarfile.open(ARCHIVE) as archive:
    available = {
        m.name[len(PREFIX):]: archive.extractfile(m).read()
        for m in archive.getmembers()
        if m.name.startswith(PREFIX) and m.isfile()
    }
    generation_sources = {}
    for rel in ["src/CMakeLists.txt", "src/CMake/config/version.h.in"]:
        data = archive.extractfile(f"XRT-{REVISION}/{rel}").read()
        target = BASE / "generation_sources" / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        generation_sources[rel] = {"sha256": hashlib.sha256(data).hexdigest(),
                                  "url": f"https://raw.githubusercontent.com/Xilinx/XRT/{REVISION}/{rel}"}

# version.h is generated by upstream CMake. Reconstruct only the macros used by
# public header ABI checks, retaining the exact revision's major/minor and patch
# default. This is explicitly a local generated shim, not a downloaded header or
# a claim about DLL build dates, branch metadata, or an installed full SDK.
available["version.h"] = b'''// R7 locally generated version macros from exact-revision CMake/version.h.in.
// Upstream src/CMakeLists.txt specifies major=2, minor=17, default patch=0.
#ifndef _XRT_VERSION_H_
#define _XRT_VERSION_H_
#define XRT_VERSION(major, minor) ((major << 16) + (minor))
#define XRT_VERSION_CODE XRT_VERSION(2, 17)
#define XRT_MAJOR(code) ((code >> 16))
#define XRT_MINOR(code) (code - ((code >> 16) << 16))
#define XRT_PATCH 0
#endif
'''

pending = ROOTS.copy()
copied = set()
headers = []
unresolved = []
while pending:
    name = pending.pop()
    if name in copied:
        continue
    data = available[name]
    destination = BASE / "include" / name
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(data)
    copied.add(name)
    headers.append({"path": str(destination.relative_to(R7)).replace("\\", "/"),
                    "source_path": PREFIX.split("/", 1)[1] + name,
                    "url": f"https://raw.githubusercontent.com/Xilinx/XRT/{REVISION}/src/runtime_src/core/include/{name}",
                    "sha256": hashlib.sha256(data).hexdigest(), "bytes": len(data)})
    if name == "version.h":
        headers[-1]["source_path"] = "locally generated ABI macros"
        headers[-1]["url"] = None
        headers[-1]["generation_sources"] = generation_sources
    for dep in re.findall(rb'^\s*#\s*include\s*"([^"]+)"', data, re.MULTILINE):
        dep = dep.decode("utf-8")
        candidates = [str(PurePosixPath(name).parent / dep), dep]
        target = next((x for x in candidates if x in available), None)
        if target is None:
            unresolved.append({"source": name, "include": dep})
        elif target not in copied:
            pending.append(target)

export_receipt = json.loads((R7 / "evidence/runtime_exports.json").read_text())
dll = next(e for e in export_receipt if Path(e["path"]).name == "xrt_coreutil.dll")
assert sha256(Path(dll["path"])) == dll["sha256"], "Installed DLL hash changed"
exports = dll["exports"]
assert len(exports) == len(set(exports)), "Duplicate exports"
(BASE / "lib").mkdir(exist_ok=True)
(BASE / "lib/xrt_coreutil.def").write_text(
    'LIBRARY xrt_coreutil.dll\nEXPORTS\n' + "".join('  ' + s + '\n' for s in exports), encoding="utf-8")
receipt = {"assembled_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(),
           "revision": REVISION, "archive_sha256": EXPECTED_ARCHIVE,
           "archive_url": f"https://codeload.github.com/Xilinx/XRT/tar.gz/{REVISION}",
           "roots": ROOTS, "headers": sorted(headers, key=lambda h: h["path"]),
           "unresolved_quoted_includes": unresolved,
           "dll_path": dll["path"], "dll_sha256": dll["sha256"], "export_count": len(exports)}
(BASE / "source_manifest.json").write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8")
print(json.dumps({"headers": len(headers), "unresolved": unresolved,
                  "exports": len(exports), "dll_sha256": dll["sha256"]}, indent=2))
