"""Interpret retained vendor diagnostics without upgrading them to calibration."""
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent

def read(path):
    return json.loads(path.read_text(encoding='utf-8-sig'))

def checked_test(report, name):
    tests = [t for d in report['logical_devices'] for t in d['tests'] if t['name'] == name]
    if len(tests) != 1:
        raise ValueError('Expected one named test')
    test = tests[0]
    errors = [v for log in test.get('log', []) for k,v in log.items() if k.lower() == 'error']
    if test['status'] != 'PASSED' or errors:
        raise ValueError({'status': test['status'], 'errors': errors})
    return test

def main():
    refs = ['evidence/vendor_verify/receipt.json','evidence/vendor_df_bw/receipt.json',
            'evidence/verify_report.json','evidence/df_bw_report.json',
            'evidence/host_inventory.json','evidence/device_report_all.json',
            'sources/xrt/TestDF_bandwidth.cpp','sources/xrt/TestIPU.cpp']
    for name in ['vendor_verify','vendor_df_bw','report_all']:
        receipt = read(ROOT/'evidence'/name/'receipt.json')
        assert receipt['returncode'] == 0 and receipt['timed_out'] is False
        assert receipt['plan_sha256'] == hashlib.sha256((ROOT/'experiment_plan.md').read_bytes()).hexdigest()
        for filename, expected in receipt['raw_sha256'].items():
            assert hashlib.sha256((ROOT/'evidence'/name/filename).read_bytes()).hexdigest() == expected
    checked_test(read(ROOT/'evidence/verify_report.json'), 'verify')
    copy = checked_test(read(ROOT/'evidence/df_bw_report.json'), 'df-bw')
    text = '\n'.join(str(v) for log in copy['log'] for v in log.values())
    elapsed = float(re.search(r"Total duration: '([\d.]+)'s", text).group(1))
    reported = float(re.search(r"bandwidth per shim DMA: '([\d.]+)'", text).group(1))
    assert abs(reported - 1/elapsed) < 0.00001  # vendor prints six decimals
    report = {
        'evidence_level':'live local Phoenix vendor diagnostic with source-audited semantics',
        'device':'RyzenAI-Phoenix / AMD IPU Device / Ryzen 7 7840H',
        'scope':'one verify launch and one 1 GiB copy selftest; not dense compute or R5 workloads',
        'test_counts':{'verify':1,'df_bw':1,'controlled_interference_pairs':0,'static_compiler_variants':0,'dynamic_variants':0},
        'verify':{'vendor_status':'PASSED','error_log_present':False,'numerical_check':False,
                  'interpretation':'launch/wait smoke only; source unconditionally overwrites catch status with PASSED'},
        'df_bw':{'vendor_status':'PASSED','error_log_present':False,
                 'host_launch_to_wait2_seconds':elapsed,
                 'host_whole_process_seconds':read(ROOT/'evidence/vendor_df_bw/receipt.json')['host_process_elapsed_s'],
                 'reported_value':reported,'reported_label':'Average bandwidth per shim DMA, GS/s',
                 'source_formula':'buffer_size_gb / host_launch_to_wait2_seconds; buffer_size_gb=1, allocation=1 GiB',
                 'interpretable_payload_rate_unit':'GiB per host second (one direction); not actual AXI rate or Gsample/s',
                 'logical_input_bytes':2**30,'logical_output_bytes':2**30,
                 'numeric_contract':'268435456 int32 values compared exactly after output sync; values generated by host rand()%4096',
                 'not_in_internal_timing':['BO allocation','input initialization','input/instruction sync','output sync','output comparison'],
                 'actual_read_bytes':None,'actual_write_bytes':None,
                 'actual_traffic_unknown_reason':'no accepted/completed bus transaction or padding/beat counter collected',
                 'input_hash':None,'input_hash_unknown_reason':'vendor does not export initialized BO data/hash',
                 'device_elapsed':None,'device_elapsed_unknown_reason':'host chrono timing only',
                 'compute_active':None,'request_latency':None,'outstanding_limit':None,'return_limit':None,
                 'counter_unknown_reason':'not exposed or configured by this vendor test'},
        'frequency':{'idle_report_H_MHz':800,'idle_report_MP_IPU_MHz':400,
                     'locked':False,'runtime_trace':None,
                     'limits':'single after-run report; not certified clock sample, DVFS/thermal state or stable run frequency'},
        'power':{'raw_report_watts':123,'accepted_measurement_watts':None,
                 'reason':'report has no sensor and source provenance/meaning must be checked; never use this field for PPA'},
        'binary_hash_capture':'post-run inventory hashes; E0 did not freeze pre-run payload or address map',
        'measurement_gate':{'functional_copy_available':True,'fixed_binary_interference_measured':False,
                            'minimum_observations_pass':False,'strong_static_established':False,
                            'mechanism_exploration_allowed':False,
                            'decision':'REFINE measurement/kernel access; do not infer no residual or propose dynamic mechanism'},
        'source_and_evidence_sha256':{p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in refs}
    }
    (ROOT/'device_probe_summary.json').write_text(json.dumps(report,indent=2),encoding='utf8')
    print(json.dumps(report,indent=2))

if __name__ == '__main__':
    main()
